# Generated by Django 5.0.1 on 2024-01-30 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='app.track'),
        ),
    ]
