# Generated by Django 5.0.1 on 2024-01-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_playlist_name_alter_playlist_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='sequence_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
