# Generated by Django 5.0.1 on 2024-01-30 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_playlist_sequence_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='track',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='sequence_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.track')),
            ],
            options={
                'unique_together': {('playlist', 'track', 'sequence_number')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='app.PlaylistTrack', to='app.track'),
        ),
    ]
