# Generated by Django 5.0.1 on 2024-01-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_playlist_track_alter_playlist_sequence_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='sequence_number',
        ),
    ]
