# Generated by Django 5.0.1 on 2024-01-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_playlist_sequence_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together={('playlist', 'sequence_number')},
        ),
    ]
