# Generated by Django 5.0.1 on 2024-01-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_playlisttrack_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together={('playlist', 'track', 'sequence_number')},
        ),
    ]
